tasks:
  - name: client-npm-install
    init: |
      cd /workspace/fullstack-admin-mern/client
      npm install
  - name: server-npm-install
    init: |
      cd /workspace/fullstack-admin-mern/server
      npm install
  - name: docker-compose-up
    init: |
     cd //workspace/fullstack-admin-mern
     docker compose build
     docker compose up