version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 8080:3000
    environment:
      REACT_APP_BASE_URL: http://localhost:8081
    volumes:
      - ./client/src/:/client/src
  server:
    build: ./server
    ports:
      - 8081:3001
    environment:
      MONGO_URL: "mongodb+srv://AselaMongoDB:FxT1mVVO6qVA101a@aselapasindu.xvnnlzi.mongodb.net/?retryWrites=true&w=majority"
      PORT: 3001
    volumes:
      - ./server/src/:/server/src