version: "3.8"

services:
  client:
    environment:
      REACT_APP_BASE_URL: http://localhost:8081
    build: ./client
    ports:
      - "8080:3000"
    volumes:
      - ./client:/client
  server:
    build: ./server
    ports:
      - "8081:3001"
    volumes:
      - ./server:/server